matrix:
  - name: Markdown
    hunspell:
      d: en_US.ISO8859-15
    dictionary:
      wordlists:
        - ${DICT_DIR}/inc_dict.txt
      output: ${DICT_DIR}/inc_dict.dic
    sources:
      - ${REPO_DIR}/docs/source/*.md
      - ${REPO_DIR}/*.md
      - ${REPO_DIR}/examples/**/*.md|!${REPO_DIR}/examples/pytorch/**/huggingface_models/**/*.md|!${REPO_DIR}/examples/README.md
      - ${REPO_DIR}/neural_compressor/**/*.md
      - ${REPO_DIR}/neural_coder/**/*.md
      - ${REPO_DIR}/neural_coder/*.md
      - ${REPO_DIR}/neural_solution/*.md
      - ${REPO_DIR}/neural_solution/docs/source/*.md
      - ${REPO_DIR}/neural_solution/examples/**/*.md
      - ${REPO_DIR}/neural_insights/*.md
