parameters:
  - name: dockerConfigName
    type: string
    default: "commonDockerConfig"
  - name: dockerFileName
    type: string
    default: "Dockerfile"
  - name: repo
    type: string
    default: "https://github.com/intel/neural-compressor"
  - name: utScriptFileName
    type: string
  - name: uploadPath
    type: string
  - name: utArtifact
    type: string
  - name: utTestMode
    type: string
    default: "coverage"
  - name: utContainerName
    type: string
    default: "utTest"
  - name: imageSource
    type: string
    default: "build"

steps:
  - template: docker-template.yml
    parameters:
      dockerConfigName: ${{ parameters.dockerConfigName }}
      repoName: "neural-compressor"
      repoTag: "py310"
      dockerFileName: "${{ parameters.dockerFileName }}"
      containerName: ${{ parameters.utContainerName }}
      repo: ${{ parameters.repo }}
      imageSource: ${{ parameters.imageSource }}

  - script: |
      docker exec -e NUMA_NODE=${NUMA_NODE} -e NUMA_CPUSET=${NUMA_CPUSET} ${{ parameters.utContainerName }} \
      bash -c "cd /neural-compressor/.azure-pipelines/scripts \
      && bash install_nc.sh ${{ parameters.utScriptFileName }} \
      && bash ut/${{ parameters.utScriptFileName }}.sh ${{ parameters.utTestMode }}"
    displayName: "Run UT"

  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      targetPath: ${{ parameters.uploadPath }}
      artifact: $(System.JobAttempt)_${{ parameters.utArtifact }}_report
      publishLocation: "pipeline"

  - ${{ if eq(parameters.utTestMode, 'coverage') }}:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: ${{ parameters.uploadPath }}
        artifact: ${{ parameters.utArtifact }}_coverage
        publishLocation: "pipeline"

  - task: Bash@3
    condition: always()
    inputs:
      targetType: "inline"
      script: |
        docker exec ${{ parameters.utContainerName }} bash -c "rm -fr /neural-compressor/* && rm -fr /neural-compressor/.* || true"
        docker stop ${{ parameters.utContainerName }}
        docker rm -vf ${{ parameters.utContainerName }} || true
    displayName: "Docker clean up"
