trigger: none

pr:
  autoCancel: true
  drafts: false
  branches:
    include:
      - master
  paths:
    include:
      - neural_compressor/common
      - neural_compressor/torch
      - neural_compressor/transformers
      - test/torch
      - test/common
      - setup.py
      - requirements_pt.txt
      - .azure-pipelines/ut-3x-pt.yml
      - .azure-pipelines/template/docker-template.yml
      - .azure-pipelines/scripts/install_nc.sh
      - .azure-pipelines/scripts/ut/run_3x_pt.sh
      - .azure-pipelines/scripts/ut/coverage.3x_pt

pool: ICX-16C

variables:
  IMAGE_NAME: "neural-compressor"
  IMAGE_TAG: "py312"
  UPLOAD_PATH: $(Build.SourcesDirectory)/log_dir
  DOWNLOAD_PATH: $(Build.SourcesDirectory)/log_dir
  ARTIFACT_NAME: "UT_coverage_report_3x_pt"
  REPO: $(Build.Repository.Uri)

stages:
  - stage: Torch
    displayName: Unit Test 3x Torch
    dependsOn: []
    jobs:
      - job:
        displayName: Unit Test 3x Torch
        steps:
          - template: template/ut-template.yml
            parameters:
              dockerConfigName: "commonDockerConfig"
              dockerFileName: "ubuntu-2404"
              repoTag: "$(IMAGE_TAG)"
              utScriptFileName: "run_3x_pt"
              uploadPath: $(UPLOAD_PATH)
              utArtifact: "ut_3x"
              utContainerName: "utTest$(NODE_LABEL)"


  - stage: Torch_baseline
    displayName: Unit Test 3x Torch baseline
    dependsOn: []
    jobs:
      - job:
        displayName: Unit Test 3x Torch baseline
        steps:
          - template: template/ut-template.yml
            parameters:
              dockerConfigName: "gitCloneDockerConfig"
              dockerFileName: "ubuntu-2404"
              repoTag: "$(IMAGE_TAG)"
              utScriptFileName: "run_3x_pt"
              uploadPath: $(UPLOAD_PATH)
              utArtifact: "ut_3x_baseline"
              repo: $(REPO)
              utContainerName: "utTest$(NODE_LABEL)"

  - stage: Coverage
    displayName: "Coverage Compare"
    pool:
      vmImage: "ubuntu-latest"
    dependsOn: [Torch, Torch_baseline]
    jobs:
      - job: CollectDatafiles
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact:
              patterns: '*_coverage/.coverage'
              path: $(DOWNLOAD_PATH)

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12'
            displayName: 'Use Python 3.12'

          - script: |
              cd ${BUILD_SOURCESDIRECTORY}
              pip install -U pip setuptools
              pip install -r requirements.txt
              python setup.py install pt
              cd ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/scripts
              bash ut/collect_log_3x.sh 3x_pt
            displayName: "Collect UT Coverage"

          - task: PublishCodeCoverageResults@2
            inputs:
              summaryFileLocation: $(Build.SourcesDirectory)/log_dir/coverage_PR/coverage.xml

          - task: PublishPipelineArtifact@1
            condition: succeededOrFailed()
            inputs:
              targetPath: $(UPLOAD_PATH)
              artifact: $(ARTIFACT_NAME)
              publishLocation: "pipeline"
