# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# CI for public repo only

name: Publish IO
permissions: {}

on:
  push:
    branches: [master]

jobs:
  build:
    if: ${{ !contains(github.repository, 'intel-innersource') }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Build Online Document
      run: |
        git config --local --get remote.origin.url
        cd docs/build_docs
        bash build.sh latest

    - name: Push to github
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build_tmp/gh-pages
        publish_branch: gh-pages
