name: Scanner BDBA

on:
  workflow_dispatch:

jobs:
  bdba_job:
    name: BDBA Scan
    uses: intel-innersource/frameworks.ai.infrastructure.code-scan-tools/.github/workflows/Scanner_Bdba.yml@one-ci-cd
    with:
      repos: ${{ github.event.repository.name }}
      refs: ${{ github.ref_name }}
      group: "22"
      runners: "['self-hosted']"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      BDBA_TOKEN: ${{ secrets.BDBA_TOKEN }}
