name: Scanner Coverity

on:
  #push:
  workflow_dispatch:

jobs:
  coverity_job:
    uses: intel-innersource/frameworks.ai.infrastructure.code-scan-tools/.github/workflows/Scanner_Coverity.yml@one-ci-cd
    with:
      repos: ${{ github.event.repository.name }}
      refs: ${{ github.ref_name }}
      projectType: python
      url: 'https://coverityent.devtools.intel.com/prod1'
      stream: 'IntelNeuralCompressor-master'
      runners: "['self-hosted']"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      USER: ${{secrets.COVERITY_USER }}
      PASSWORD : ${{secrets.COVERITY_PASSWORD }}
