name: Virus Scan

on:
  workflow_dispatch:

jobs:
  virus:
    name: McAfee Virus Scan
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Execute Scan
        uses: intel-innersource/frameworks.devops.github.actions.mcafee@main
        with:
          scan_path: neural_compressor
